### ISSUE TITLE
On New Entry -> Save. An Error is thrown (see attached)

### ISSUE THREAD

**Issue by dmyers2004** [adamfairholm/PyroStreams-Multiple-Relationships#16]
On New Entry -> Save. An Error is thrown but it seems to save fine because after you view the record it seems fine as well as any additional saves. I'll try to take a look tomorrow at it.

![Screen Shot 2013-03-05 at 10 02 55 PM](https://f.cloud.github.com/assets/254378/225903/ad07458c-860a-11e2-8f40-a3246748186f.png)

**Comment by dmyers2004** [comment]
Ok change line 88 to 

``` php
if (is_numeric($row_id = @$form_data['row_edit_id'])) {
```

**Comment by ChristianGiupponi** [comment]
Thanks it works
