### ISSUE TITLE
Still not populated when edit stream under pyrocms v2.2 (pro)

### ISSUE THREAD

**Issue by peet86** [adamfairholm/PyroStreams-Multiple-Relationships#23]
Hi!

It seems the field not populated when you edit a stream entry.
All data in the databse seems to be ok after I added some relation and saved the entry, but when I want to edit again, the relationship field is empty.

Peter

**Comment by peet86** [comment]
Ok, the problem is: when is use this in the pyro blog stream and editing a plog post, the form_output() method (line 363) $entry_id parameter is always empty.. -> the join query result is empty -> no data in multiple relation field.
When I hard code the relationship row id ($entry_id=162), the field works good.

**Comment by peet86** [comment]
So this is a pyrocms bug,  the post id parameter missing in  blog / admin.php [401] ->set('stream_fields',[....] $values, $post->id))

**Comment by adamfairholm** [comment]
This is a Pyro bug, fixed here for 2.2.1:
https://github.com/pyrocms/pyrocms/commit/2126da17a61a8cefe2729628e18a48e5fb2dae14
