### ISSUE TITLE
Order by a relationship fieldtype

### ISSUE THREAD

**Issue by jsftwww** [adamfairholm/PyroStreams-Multiple-Relationships#37]
Is it possible to order the results by a relational field?

The following syntax is what I attempted:

```
<ul>
{{ dogs order_by="classification:class_name" sort="asc" }}
  <li>{{ classification:class_name }}</li>
{{ dogs }}
</ul>
```

Output: 500 error.

**Comment by tapankumar** [comment]
@toyinonline Have you got any solution on your issue?

I have exact same requirement.

**Comment by jsftwww** [comment]
This was a while ago, and I never got a response. I think I ended up switching the organization. Fortunately, it was just an idea I had, not a client requirement. I wasn't able to implement this syntax.

**Comment by RyanThompson** [comment]
Unfortunately this is not possible in 2.2.x - Soon guys..
