### ISSUE TITLE
Multiple Relationship Issue

### ISSUE THREAD

**Issue by tapankumar** [adamfairholm/PyroStreams-Multiple-Relationships#42]
Hi,

I have two streams.

home_planner & usage

usage stream is having multi relationship with home_planner via multi relationship field.

I want to access all usage of particular home_planner and to achieve this i have below code.

{{ streams:cycle stream="home_planner" where="`status`='1' AND `id`='1'" }}
            {{ usage }}
                    {{ name }}
            {{ usage }}
{{ /streams:cycle }}

However usage loop is not working.

Please suggest if i am trying to achieve this with right syntax.

Thanks
Tapan Thapa

**Comment by aroon9002ahmed** [comment]
{{ usage }}
{{ name }}
{{ /usage }}

you have to close tag {{ /usage }}
