### ISSUE TITLE
Users Profile Fields error

### ISSUE THREAD

**Issue by aroon9002ahmed** [adamfairholm/PyroStreams-Multiple-Relationships#46]
Hello
i just create a user Profile Fields "category"
i got this error in user edit page:
A PHP Error was encountered

Severity: Notice

Message: Undefined property: stdClass::$category

Filename: controllers/users.php

Line Number: 801

**Comment by RyanThompson** [comment]
What version are you using?

**Comment by aroon9002ahmed** [comment]
Multiple Relationships Field Type 2.0.1
pyrocms 2.2.5

**Comment by aroon9002ahmed** [comment]
i have test it on new pyrocms to check it ... but give me the same error
![website edit users](https://cloud.githubusercontent.com/assets/7735634/8488829/2e9651e4-2116-11e5-93af-b4fb27867244.png)

**Comment by RyanThompson** [comment]
This is a strict notice. If you decrease your php error output to errors only you should be good.

Sent from my iPhone

On Jul 2, 2015, at 4:59 PM, aroon9002ahmed <notifications@github.com<mailto:notifications@github.com>> wrote:

i have test it on new pyrocms to check it ... but give me the same error
[website edit users]https://cloud.githubusercontent.com/assets/7735634/8488829/2e9651e4-2116-11e5-93af-b4fb27867244.png

##

**Comment by RyanThompson** [comment]
Or don't enforce strict.

Sent from my iPhone

On Jul 2, 2015, at 4:59 PM, aroon9002ahmed <notifications@github.com<mailto:notifications@github.com>> wrote:

i have test it on new pyrocms to check it ... but give me the same error
[website edit users]https://cloud.githubusercontent.com/assets/7735634/8488829/2e9651e4-2116-11e5-93af-b4fb27867244.png

##
